force_cast: warning
force_try:
  severity: warning # explicitly

line_length: 120

type_body_length:
  - 400 # warning
  - 600 # error

file_length:
  warning: 800
  error: 1200

nesting:
  type_level: 2
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - url
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)